#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Module-Util
Version  : 1.09
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/M/MA/MATTLAW/Module-Util-1.09.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/M/MA/MATTLAW/Module-Util-1.09.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libm/libmodule-util-perl/libmodule-util-perl_1.09-3.debian.tar.xz
Summary  : 'Module name tools and transformations'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-Module-Util-bin
Requires: perl-Module-Util-man
Requires: perl(Module::Build::Compat)
BuildRequires : perl(Module::Build::Compat)

%description
NAME
Module::Util - Module name tools and transformations
SYNOPSIS
use Module::Util qw( :all );

%package bin
Summary: bin components for the perl-Module-Util package.
Group: Binaries
Requires: perl-Module-Util-man

%description bin
bin components for the perl-Module-Util package.


%package man
Summary: man components for the perl-Module-Util package.
Group: Default

%description man
man components for the perl-Module-Util package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Module-Util-1.09
mkdir -p %{_topdir}/BUILD/Module-Util-1.09/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Module-Util-1.09/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Module/Util.pm

%files bin
%defattr(-,root,root,-)
/usr/bin/pm_which

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/pm_which.1
/usr/share/man/man3/Module::Util.3
